# Bitcoin Market Sentiment Analysis & Price Prediction

## Project Objective
The objective of this project is to predict Bitcoin execution prices using market trading data and sentiment analysis. This project includes data cleaning, exploratory data analysis, feature engineering, machine learning model development, evaluation, and deployment preparation.

In [ ]:
#Import Libraries
# Ignore warning messages
import warnings
warnings.filterwarnings("ignore")
# Data manipulation
import pandas as pd
import numpy as np
# Data visualization
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# Display graphs inside the notebook
%matplotlib inline

In [ ]:
#Load Dataset
df = pd.read_csv('merged_df.csv')

In [ ]:
df.head()

,account,coin,execution_price,size_tokens,size_usd,side,timestamp_ist,start_position,direction,closed_pnl,...,timestamp_x,date,timestamp_y,value,classification,profit_flag,hour,day_of_week,is_weekend,sentiment_score
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-02-12 22:50:00,0.000000,Buy,0.0,...,1.730000e+12,2024-02-12,1.707716e+09,70.0,Greed,0,22,Monday,0,3.0
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-02-12 22:50:00,986.524596,Buy,0.0,...,1.730000e+12,2024-02-12,1.707716e+09,70.0,Greed,0,22,Monday,0,3.0
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-02-12 22:50:00,1002.518996,Buy,0.0,...,1.730000e+12,2024-02-12,1.707716e+09,70.0,Greed,0,22,Monday,0,3.0
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-02-12 22:50:00,1146.558564,Buy,0.0,...,1.730000e+12,2024-02-12,1.707716e+09,70.0,Greed,0,22,Monday,0,3.0
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-02-12 22:50:00,1289.488521,Buy,0.0,...,1.730000e+12,2024-02-12,1.707716e+09,70.0,Greed,0,22,Monday,0,3.0

In [ ]:
df.tail()

,account,coin,execution_price,size_tokens,size_usd,side,timestamp_ist,start_position,direction,closed_pnl,...,timestamp_x,date,timestamp_y,value,classification,profit_flag,hour,day_of_week,is_weekend,sentiment_score
211219,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,382.2,420.80,SELL,2025-04-25 15:35:00,7546.6,Close Long,-20.2566,...,1.750000e+12,2025-04-25,1.745559e+09,60.0,Greed,0,15,Friday,0,3.0
211220,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,2124.1,2338.63,SELL,2025-04-25 15:35:00,7164.4,Close Long,-112.5773,...,1.750000e+12,2025-04-25,1.745559e+09,60.0,Greed,0,15,Friday,0,3.0
211221,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,423.4,466.16,SELL,2025-04-25 15:35:00,5040.3,Close Long,-22.4402,...,1.750000e+12,2025-04-25,1.745559e+09,60.0,Greed,0,15,Friday,0,3.0
211222,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,3599.8,3963.38,SELL,2025-04-25 15:35:00,4616.9,Close Long,-190.7894,...,1.750000e+12,2025-04-25,1.745559e+09,60.0,Greed,0,15,Friday,0,3.0
211223,0x72743ae2822edd658c0c50608fd7c5c501b2afbd,FARTCOIN,1.101,1017.1,1119.83,SELL,2025-04-25 15:35:00,1017.1,Close Long,-53.9063,...,1.750000e+12,2025-04-25,1.745559e+09,60.0,Greed,0,15,Friday,0,3.0

In [ ]:
# Number of rows and columns
rows, columns = df.shape
print(f"Number of Rows    : {rows}")
print(f"Number of Columns : {columns}")

Number of Rows    : 211224
Number of Columns : 25

In [ ]:
#column Names
df.columns

Index(['account', 'coin', 'execution_price', 'size_tokens', 'size_usd', 'side',
       'timestamp_ist', 'start_position', 'direction', 'closed_pnl',
       'transaction_hash', 'order_id', 'crossed', 'fee', 'trade_id',
       'timestamp_x', 'date', 'timestamp_y', 'value', 'classification',
       'profit_flag', 'hour', 'day_of_week', 'is_weekend', 'sentiment_score'],
      dtype='object')

In [ ]:
#Datasset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   account           211224 non-null  object
 1   coin              211224 non-null  object
 2   execution_price   211224 non-null  float64
 3   size_tokens       211224 non-null  float64
 4   size_usd          211224 non-null  float64
 5   side              211224 non-null  object
 6   timestamp_ist     211224 non-null  object
 7   start_position    211224 non-null  float64
 8   direction         211224 non-null  object
 9   closed_pnl        211224 non-null  float64
 10  transaction_hash  211224 non-null  object
 11  order_id          211224 non-null  int64
 12  crossed           211224 non-null  bool
 13  fee               211224 non-null  float64
 14  trade_id          211224 non-null  float64
 15  timestamp_x       211224 non-null  float64
 16  date              211224 non-null  object
 17  timestamp_y       167857 non-null  float64
 18  value             167857 non-null  float64
 19  classification    167857 non-null  object
 20  profit_flag       211224 non-null  int64
 21  hour              211224 non-null  int64
 22  day_of_week       211224 non-null  object
 23  is_weekend        211224 non-null  int64
 24  sentiment_score   167857 non-null  float64
dtypes: bool(1), float64(11), int64(4), object(9)
memory usage: 38.9+ MB

In [ ]:
# Summary statistics for numerical columns
df.describe()

,execution_price,size_tokens,size_usd,start_position,closed_pnl,order_id,fee,trade_id,timestamp_x,timestamp_y,value,profit_flag,hour,is_weekend,sentiment_score
count,211224.000000,2.112240e+05,2.112240e+05,2.112240e+05,211224.000000,2.112240e+05,211224.000000,2.112240e+05,2.112240e+05,1.678570e+05,167857.000000,211224.000000,211224.000000,211224.000000,167857.000000
mean,11414.723350,4.623365e+03,5.639451e+03,-2.994625e+04,48.749001,6.965388e+10,1.163967,5.628549e+14,1.737744e+12,1.737330e+09,54.698547,0.411265,11.680013,0.212457,2.352330
std,29447.654868,1.042729e+05,3.657514e+04,6.738074e+05,919.164828,1.835753e+10,6.758854,3.257565e+14,8.689920e+09,8.980998e+06,20.253089,0.492064,7.363057,0.409047,1.181169
min,0.000005,8.740000e-07,0.000000e+00,-1.433463e+07,-117990.104100,1.732711e+08,-1.175712,0.000000e+00,1.680000e+12,1.672897e+09,10.000000,0.000000,0.000000,0.000000,0.000000
25%,4.854700,2.940000e+00,1.937900e+02,-3.762311e+02,0.000000,5.983853e+10,0.016121,2.810000e+14,1.740000e+12,1.734586e+09,37.000000,0.000000,5.000000,0.000000,1.000000
50%,18.280000,3.200000e+01,5.970450e+02,8.472793e+01,0.000000,7.442939e+10,0.089578,5.620000e+14,1.740000e+12,1.740116e+09,54.000000,0.000000,12.000000,0.000000,2.000000
75%,101.580000,1.879025e+02,2.058960e+03,9.337278e+03,5.792797,8.335543e+10,0.393811,8.460000e+14,1.740000e+12,1.743399e+09,73.000000,1.000000,19.000000,0.000000,3.000000
max,109004.000000,1.582244e+07,3.921431e+06,3.050948e+07,135329.090100,9.014923e+10,837.471593,1.130000e+15,1.750000e+12,1.746164e+09,94.000000,1.000000,23.000000,1.000000,4.000000

In [ ]:
# Count missing values in each column
missing_values = df.isnull().sum()
missing_values

account                 0
coin                    0
execution_price         0
size_tokens             0
size_usd                0
side                    0
timestamp_ist           0
start_position          0
direction               0
closed_pnl              0
transaction_hash        0
order_id                0
crossed                 0
fee                     0
trade_id                0
timestamp_x             0
date                    0
timestamp_y         43367
value               43367
classification      43367
profit_flag             0
hour                    0
day_of_week             0
is_weekend              0
sentiment_score     43367
dtype: int64

In [ ]:
# Calculate the percentage of missing values
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

sentiment_score     20.531284
timestamp_y         20.531284
value               20.531284
classification      20.531284
size_usd             0.000000
coin                 0.000000
execution_price      0.000000
size_tokens          0.000000
account              0.000000
direction            0.000000
start_position       0.000000
timestamp_ist        0.000000
side                 0.000000
closed_pnl           0.000000
transaction_hash     0.000000
order_id             0.000000
crossed              0.000000
date                 0.000000
timestamp_x          0.000000
trade_id             0.000000
fee                  0.000000
profit_flag          0.000000
hour                 0.000000
day_of_week          0.000000
is_weekend           0.000000
dtype: float64

In [ ]:
# Count duplicate rows
duplicate_rows = df.duplicated().sum()
print(f"Duplicate Rows: {duplicate_rows}")

Duplicate Rows: 0

In [ ]:
# Remove duplicate records
bitcoin_data = df.drop_duplicates()
print("Duplicate rows removed successfully.")

Duplicate rows removed successfully.

In [ ]:
# Store the original number of rows
rows_before_cleaning = len(bitcoin_data)
# Remove rows containing missing values
bitcoin_data = bitcoin_data.dropna()
# Store the remaining number of rows
rows_after_cleaning = len(bitcoin_data)
print(f"Rows before cleaning : {rows_before_cleaning}")
print(f"Rows after cleaning  : {rows_after_cleaning}")
print(f"Rows removed         : {rows_before_cleaning - rows_after_cleaning}")

Rows before cleaning : 211224
Rows after cleaning  : 167857
Rows removed         : 43367

In [ ]:
# Ensure there are no missing values
bitcoin_data.isnull().sum()

account             0
coin                0
execution_price     0
size_tokens         0
size_usd            0
side                0
timestamp_ist       0
start_position      0
direction           0
closed_pnl          0
transaction_hash    0
order_id            0
crossed             0
fee                 0
trade_id            0
timestamp_x         0
date                0
timestamp_y         0
value               0
classification      0
profit_flag         0
hour                0
day_of_week         0
is_weekend          0
sentiment_score     0
dtype: int64

In [ ]:
# Display the data type of each column
bitcoin_data.dtypes

account              object
coin                 object
execution_price     float64
size_tokens         float64
size_usd            float64
side                 object
timestamp_ist        object
start_position      float64
direction            object
closed_pnl          float64
transaction_hash     object
order_id              int64
crossed                bool
fee                 float64
trade_id            float64
timestamp_x         float64
date                 object
timestamp_y         float64
value               float64
classification       object
profit_flag           int64
hour                  int64
day_of_week          object
is_weekend            int64
sentiment_score     float64
dtype: object

In [ ]:
# Display unique values for every column
for column in bitcoin_data.columns:
    print(f"{column}: {bitcoin_data[column].nunique()} unique values")

account: 32 unique values
coin: 243 unique values
execution_price: 52101 unique values
size_tokens: 50905 unique values
size_usd: 98746 unique values
side: 2 unique values
timestamp_ist: 23699 unique values
start_position: 157046 unique values
direction: 11 unique values
closed_pnl: 72933 unique values
transaction_hash: 80114 unique values
order_id: 42906 unique values
crossed: 2 unique values
fee: 114667 unique values
trade_id: 2713 unique values
timestamp_x: 7 unique values
date: 449 unique values
timestamp_y: 449 unique values
value: 70 unique values
classification: 5 unique values
profit_flag: 2 unique values
hour: 24 unique values
day_of_week: 7 unique values
is_weekend: 2 unique values
sentiment_score: 5 unique values

In [ ]:
# Save the cleaned dataset for further analysis
bitcoin_data.to_csv("cleaned_bitcoin_data.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [ ]:
print("Final Dataset Shape:")
print(bitcoin_data.shape)

Final Dataset Shape:
(167857, 25)

In [ ]:
from google.colab import files
files.download("cleaned_bitcoin_data.csv")